// <auto-generated />
using System;
using Messenger.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseMigrationTool.Migrations
{
    [DbContext(typeof(IEMessengerDbContext))]
    [Migration("20251228164027_change-messageRecipient-column")]
    partial class changemessageRecipientcolumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Persian_100_CS_AI")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Messenger.Models.Models.BlockedUser", b =>
                {
                    b.Property<int>("BlockedUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlockedUserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockedUserId"));

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Comment")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("BlockedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("BlockedUsers");
                });

            modelBuilder.Entity("Messenger.Models.Models.Channel", b =>
                {
                    b.Property<long>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ChannelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChannelId"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ChannelId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Messenger.Models.Models.ChannelMember", b =>
                {
                    b.Property<long>("ChanelMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ChanelMemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChanelMemberId"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChannelID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("MemberRoleType")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("ChanelMemberId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("ChannelMembers");
                });

            modelBuilder.Entity("Messenger.Models.Models.ClassGroup", b =>
                {
                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClassGroupName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClassTiming")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<int?>("LeftSes")
                        .HasColumnType("int");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("TeacherUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("TeacherUserID");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ClassId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TeacherUserId" }, "IX_ClassGroups_TeacherUserId");

                    b.ToTable("ClassGroups");
                });

            modelBuilder.Entity("Messenger.Models.Models.ClassGroupMessagesView", b =>
                {
                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClassTiming")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("isHidden");

                    b.Property<bool>("IsPin")
                        .HasColumnType("bit")
                        .HasColumnName("isPin");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit")
                        .HasColumnName("isPrivate");

                    b.Property<int?>("LeftSes")
                        .HasColumnType("int");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("MessageDateTime")
                        .HasColumnType("datetime");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.Property<long?>("ReplyMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReplyMessageID");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SenderUserID");

                    b.Property<long>("TeacherUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("TeacherUserID");

                    b.ToTable((string)null);

                    b.ToView("ClassGroupMessagesView", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.FileExtension", b =>
                {
                    b.Property<int>("FileExtensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileExtensionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileExtensionId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("FontAwesome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("FileExtensionId")
                        .HasName("PK_AllowFileExtention_1");

                    b.ToTable("FileExtension", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasColumnName("isEdited");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("isHidden");

                    b.Property<bool>("IsPin")
                        .HasColumnType("bit")
                        .HasColumnName("isPin");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("MessageDateTime")
                        .HasColumnType("datetime");

                    b.Property<byte>("MessageType")
                        .HasColumnType("tinyint");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PinnedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReplyMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReplyMessageID");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SenderUserID");

                    b.HasKey("MessageId");

                    b.HasIndex("ReplyMessageId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageFile", b =>
                {
                    b.Property<long>("MessageFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageFileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageFileId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("FileExtensionId")
                        .HasColumnType("int")
                        .HasColumnName("FileExtensionID");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileThumbPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("if file type is Image, this filed has value");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UploaderUserId")
                        .HasColumnType("bigint");

                    b.HasKey("MessageFileId");

                    b.HasIndex("FileExtensionId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageFile", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageFoulReport", b =>
                {
                    b.Property<long>("MessageFoulReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageFoulReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageFoulReportId"));

                    b.Property<string>("FoulDesc")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<DateTime>("FoulReportDateTime")
                        .HasColumnType("datetime");

                    b.Property<long>("FoulReporterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("FoulReporterUserID");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.HasKey("MessageFoulReportId");

                    b.HasIndex("FoulReporterUserId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageFoulReport", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageRead", b =>
                {
                    b.Property<long>("ReadMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ReadMessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReadMessageId"));

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("ClassGroup = group\r\nChannelGroup = channel\r\nPrivate = private chat");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.Property<DateTime>("ReadDateTime")
                        .HasColumnType("datetime");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasComment("ایدی چت مورد نظر - گروه یا کانال ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("ReadMessageId");

                    b.HasIndex("MessageId");

                    b.HasIndex(new[] { "UserId", "GroupType", "TargetId", "MessageId" }, "IX_MessageRead_User_Group_Target_Message")
                        .IsDescending(false, false, false, true);

                    b.ToTable("MessageRead", null, t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageRecipient", b =>
                {
                    b.Property<long>("MessageRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageRecipientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageRecipientId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.Property<DateTime?>("ReadDateTime")
                        .HasColumnType("datetime");

                    b.Property<long>("UserConversationId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserConversationId");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("MessageRecipientId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "MessageId", "UserConversationId" }, "IX_MessageRecipients_Message_Recipient");

                    b.HasIndex(new[] { "UserConversationId" }, "IX_MessageRecipients_UserConversationId");

                    b.ToTable("MessageRecipients", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageSaved", b =>
                {
                    b.Property<long>("MessageSavedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageSavedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageSavedId"));

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.Property<DateTime>("SaveDateTime")
                        .HasColumnType("datetime");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("MessageSavedId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageSaved", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageText", b =>
                {
                    b.Property<long>("MessageTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageTextID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageTextId"));

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.Property<string>("MessageTxt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageTextId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageText", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.MessengerEventLog", b =>
                {
                    b.Property<long>("MessengerLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessengerLogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessengerLogId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.HasKey("MessengerLogId")
                        .HasName("PK_EventLog");

                    b.ToTable("MessengerEventLog", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.PersonelChatAccess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AccessSendMessageInChat")
                        .HasColumnType("bit")
                        .HasComment("مجاز برای ارسال پیام در گروه چت یا کانال\r\n");

                    b.Property<bool>("AccessToStudentMessage")
                        .HasColumnType("bit")
                        .HasComment("مجاز برای ارسال پیام به اعضای گروه چت یا کانال");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("ClassGroup = group\r\nChannelGroup = channel\r\n");

                    b.Property<long>("PersonelId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelChatAccess", null, t =>
                        {
                            t.HasComment("نگهداری ایدی چت و پرسنل جهت اینکه پرسنل مورد نظر دسترسی به ارسال پیام در گروه و ارسال به افراد ان گروه را دارد یا خیر.\r\n");
                        });
                });

            modelBuilder.Entity("Messenger.Models.Models.PrivateChatConversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("User1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("User2Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("PrivateChatConversations");
                });

            modelBuilder.Entity("Messenger.Models.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<string>("DeptName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoginToken")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NameFamily")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProfilePicName")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RoleFaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Messenger.Models.Models.UserClassGroup", b =>
                {
                    b.Property<long>("UserClassGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserClassGroupID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserClassGroupId"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClassID");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint");

                    b.Property<byte>("MemberRoleType")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("UserClassGroupId")
                        .HasName("PK_UserClassGroup_1");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClassGroup", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.ViewClassGroup", b =>
                {
                    b.Property<long>("ViewClassGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ViewClassGroupID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ViewClassGroupId"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClassID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<DateTime>("ViewDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("ViewClassGroupId");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("ViewClassGroup", (string)null);
                });

            modelBuilder.Entity("Messenger.Models.Models.WebPushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("Messenger.Models.Models.BlockedUser", b =>
                {
                    b.HasOne("Messenger.Models.Models.User", "User")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BlockedUsers_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messenger.Models.Models.Channel", b =>
                {
                    b.HasOne("Messenger.Models.Models.User", "CreatorUser")
                        .WithMany("Channels")
                        .HasForeignKey("CreatorUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Channels_Users");

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("Messenger.Models.Models.ChannelMember", b =>
                {
                    b.HasOne("Messenger.Models.Models.Channel", "Channel")
                        .WithMany("ChannelMembers")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_ChannelMembers_Channels");

                    b.HasOne("Messenger.Models.Models.User", "User")
                        .WithMany("ChannelMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ChannelMembers_Users");

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messenger.Models.Models.ClassGroup", b =>
                {
                    b.HasOne("Messenger.Models.Models.User", null)
                        .WithMany("ClassGroups")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Messenger.Models.Models.Message", b =>
                {
                    b.HasOne("Messenger.Models.Models.Message", "ReplyMessage")
                        .WithMany("InverseReplyMessage")
                        .HasForeignKey("ReplyMessageId")
                        .HasConstraintName("FK_Messages_Messages");

                    b.HasOne("Messenger.Models.Models.User", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Users");

                    b.Navigation("ReplyMessage");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageFile", b =>
                {
                    b.HasOne("Messenger.Models.Models.FileExtension", "FileExtension")
                        .WithMany("MessageFiles")
                        .HasForeignKey("FileExtensionId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageFile_FileExtension");

                    b.HasOne("Messenger.Models.Models.Message", "Message")
                        .WithMany("MessageFiles")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_MessageFile_Messages");

                    b.Navigation("FileExtension");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageFoulReport", b =>
                {
                    b.HasOne("Messenger.Models.Models.User", "FoulReporterUser")
                        .WithMany("MessageFoulReports")
                        .HasForeignKey("FoulReporterUserId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageFoulReport_Users");

                    b.HasOne("Messenger.Models.Models.Message", "Message")
                        .WithMany("MessageFoulReports")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MessageFoulReport_Messages");

                    b.Navigation("FoulReporterUser");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageRead", b =>
                {
                    b.HasOne("Messenger.Models.Models.Message", "Message")
                        .WithMany("MessageReads")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MessageRead_Messages");

                    b.HasOne("Messenger.Models.Models.User", "User")
                        .WithMany("MessageReads")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageRead_Users");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageRecipient", b =>
                {
                    b.HasOne("Messenger.Models.Models.Message", "Message")
                        .WithMany("MessageRecipients")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MessageRecipients_Messages");

                    b.HasOne("Messenger.Models.Models.PrivateChatConversation", "Conversation")
                        .WithMany("MessageRecipients")
                        .HasForeignKey("UserConversationId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageRecipients_PrivateChatConversations");

                    b.HasOne("Messenger.Models.Models.User", null)
                        .WithMany("MessageRecipients")
                        .HasForeignKey("UserId");

                    b.Navigation("Conversation");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageSaved", b =>
                {
                    b.HasOne("Messenger.Models.Models.Message", "Message")
                        .WithMany("MessageSaveds")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MessageSaved_Messages");

                    b.HasOne("Messenger.Models.Models.User", "User")
                        .WithMany("MessageSaveds")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageSaved_Users");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messenger.Models.Models.MessageText", b =>
                {
                    b.HasOne("Messenger.Models.Models.Message", "Message")
                        .WithMany("MessageTexts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MessageText_Messages");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Messenger.Models.Models.PersonelChatAccess", b =>
                {
                    b.HasOne("Messenger.Models.Models.User", "Personel")
                        .WithMany("PersonelChatAccesses")
                        .HasForeignKey("PersonelId")
                        .IsRequired()
                        .HasConstraintName("FK_PersonelChatAccess_Users");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Messenger.Models.Models.PrivateChatConversation", b =>
                {
                    b.HasOne("Messenger.Models.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .IsRequired()
                        .HasConstraintName("FK_PrivateChatConversations_User1");

                    b.HasOne("Messenger.Models.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .IsRequired()
                        .HasConstraintName("FK_PrivateChatConversations_User2");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Messenger.Models.Models.UserClassGroup", b =>
                {
                    b.HasOne("Messenger.Models.Models.ClassGroup", "Class")
                        .WithMany("UserClassGroups")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserClassGroup_ClassGroups");

                    b.HasOne("Messenger.Models.Models.User", "User")
                        .WithMany("UserClassGroups")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserClassGroup_Users");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messenger.Models.Models.ViewClassGroup", b =>
                {
                    b.HasOne("Messenger.Models.Models.ClassGroup", "Class")
                        .WithMany("ViewClassGroups")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ViewClassGroup_ClassGroups");

                    b.HasOne("Messenger.Models.Models.User", "User")
                        .WithMany("ViewClassGroups")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ViewClassGroup_Users");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messenger.Models.Models.Channel", b =>
                {
                    b.Navigation("ChannelMembers");
                });

            modelBuilder.Entity("Messenger.Models.Models.ClassGroup", b =>
                {
                    b.Navigation("UserClassGroups");

                    b.Navigation("ViewClassGroups");
                });

            modelBuilder.Entity("Messenger.Models.Models.FileExtension", b =>
                {
                    b.Navigation("MessageFiles");
                });

            modelBuilder.Entity("Messenger.Models.Models.Message", b =>
                {
                    b.Navigation("InverseReplyMessage");

                    b.Navigation("MessageFiles");

                    b.Navigation("MessageFoulReports");

                    b.Navigation("MessageReads");

                    b.Navigation("MessageRecipients");

                    b.Navigation("MessageSaveds");

                    b.Navigation("MessageTexts");
                });

            modelBuilder.Entity("Messenger.Models.Models.PrivateChatConversation", b =>
                {
                    b.Navigation("MessageRecipients");
                });

            modelBuilder.Entity("Messenger.Models.Models.User", b =>
                {
                    b.Navigation("BlockedUsers");

                    b.Navigation("ChannelMembers");

                    b.Navigation("Channels");

                    b.Navigation("ClassGroups");

                    b.Navigation("MessageFoulReports");

                    b.Navigation("MessageReads");

                    b.Navigation("MessageRecipients");

                    b.Navigation("MessageSaveds");

                    b.Navigation("Messages");

                    b.Navigation("PersonelChatAccesses");

                    b.Navigation("UserClassGroups");

                    b.Navigation("ViewClassGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
